# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.allyth.me
title: Alexandra Maria Theodorescu
email: 
author: Alexandra
description:
collections:
  posts:
    output: true
  drawings:
    output: false
  photos:
    output: false

defaults:
  - scope:
      collection: drawings
    values:
      showTitle: true
      showOnHomepage: false
  - scope:
      collection: photos
    values:
      showTitle: true

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap
  - title: linkedin
    url: 

menu:
  - text: Home
    url: /
  - text: Drawing
    url: /drawing/
  - text: Photography
    url: /photography/
  - text: Blog
    url: /blog/
  - text: About
    url: /about/