# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.allyth.me
title: Maria Alexandra Theodorescu
email: 
author: Alexandra
description:
collections:
  posts:
    output: true
  visualArts:
    output: false
  photos:
    output: false

defaults:
  - scope:
      collection: visualArts
    values:
      showTitle: true
      showOnHomepage: false

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

menu:
  - text: Home
    url: /
  - text: Visual Arts
    url: /visual-arts/
  - text: Blog
    url: /blog/
  - text: About
    url: /about/